#!/bin/sh

/usr/bin/invoke_app "$@" -C "start_jupyter -T @tool bin/test_notebook.ipynb" \
                                               -t quorumsensing \
                                               -u anaconda3-5.1
